on:
  push:
    branches:
      - update-doc
      - master
jobs:
  deploy-dist:
    name: deploy-dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm install
      - run: npm run build
      - run: sed -i 's/dist/enable-dist-branch/g' ./.gitignore
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.PUBLISH_DIST_DEPLOY_KEY }}
          PUBLISH_BRANCH: lib
          PUBLISH_DIR: ./
        with:
          forceOrphan: true
